### PR TITLE
MSPA-1445 Include additional detail in overlapping region error

### PR DESCRIPTION
**Pull request by nigelmegitt**
Example error message resulting from this change:

```
ebu_tt_live.errors.OverlappingActiveElementsError: The EBU-TT-D spec forbids overlapping active areas. Element C530 references regionid=R3, origin=12% 79.348%, extent=76% 15.652% and Element C531 references regionid=agr_2_20_38_2_after, origin=15.75% 79.348%, extent=72.25% 7.826%.
```

### CODE REVIEW

**Review by mm326 — COMMENTED** [review]
Looks good,
Currently we test that an exception is thrown 
`Then application should exit with error OverlappingActiveElementsError`
 I'm wondering is there a way we could get the exception message on the bdd tests?

**Comment by nigelmegitt** [comment]
Yeah I wondered that too. At the moment the BDD test uses a `with` handler. I'm sure it's possible to assert against the value of the received exception. I'll take a look.

**Comment by mm326** [comment]
> Yeah I wondered that too. At the moment the BDD test uses a `with` handler. I'm sure it's possible to assert against the value of the received exception. I'll take a look.

If it's not simple dw we could have a test case in distiller maybe?

**Comment by nigelmegitt** [comment]
> If it's not simple dw we could have a test case in distiller maybe?

Probably makes sense to keep the test with the LIT since that's where the code is.

**Review by mm326 — APPROVED** [review]

**Pull request merged**
